### ISSUE TITLE
[POST] 성분 추가

### ISSUE THREAD

**Issue by 2Re-play** [CareDirection/CareDirection-Server#48]
get api들을 하기 위해서 여러 성분 데이터를 api를 통해 DB에 저장할 ADMIN api

- [x] task 나누기

- [x] request Json Body 작성

- [x] URL 작성

- [x] Git Wiki 완성

- [x] Query 작성

- [x] 로직 작성

- [x] 이미지 추가 로직 작성

**Comment by malibinYun** [comment]
이미지 등록시키는 기능 추가시켜야함
